default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  encoding: <%= ENV['DATABASE_ENCODING'] || 'unicode' %>
  pool: <%= ENV['DATABASE_POOL'] || '5' %>
  timeout: <%= ENV['DATABASE_TIMEOUT'] || '5000' %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: acme_development

test:
  <<: *default
  database: acme_test

production: *default

