
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: nouvak@1234
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: acme_development


test:
  <<: *default
  database: acme_test


production:
  <<: *default
  database: acme_production
  username: acme
  password: <%= ENV["ACME_DATABASE_PASSWORD"] %>
