default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  encoding: <%= ENV['DATABASE_ENCODING'] || 'unicode' %>
  pool: <%= ENV['DATABASE_POOL'] || '5' %>
  timeout: <%= ENV['DATABASE_TIMEOUT'] || '5000' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'nouvak@1234' %>

development:
  <<: *default
  database: acme_development

test:
  <<: *default
  database: acme_test

production:
  <<: *default
  database: acme_production
  url: <%= ENV['DATABASE_URL'] %>
