# test
name: deploy-main
push:
  branches:
    - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Container registry
        uses: actions/checkout@v1

      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
